package DailyChallengeQuestions;

/*
389. Find the Difference

Link: https://leetcode.com/problems/find-the-difference/

You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
 */

public class FindTheDifference {
	
	class Solution {
	    public char findTheDifference(String s, String t) {
	        int i = -1,sum=0;
	        while((++i)<s.length()) {
	            sum += t.charAt(i)-s.charAt(i);
	        }
	        sum += t.charAt(i);
	        return (char)sum;
	    }
	}

}
